name: Sync LeetCode Solutions

on:
  workflow_dispatch:  # Allows you to trigger the workflow manually
  schedule:
    - cron: "0 8 * * 6"  # Runs every Saturday at 8 AM

jobs:
  sync:
    runs-on: ubuntu-latest  # Uses the latest version of Ubuntu for the runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # Checks out the repository code

- name: Sync LeetCode Solutions
  uses: your-username/leetcode-sync@main
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}
    leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
    leetcode-session: ${{ secrets.LEETCODE_SESSION_TOKEN }}
    destination-folder: solutions
    verbose: true
    commit-header: "[LeetCode Sync]"
