name: Sync LeetCode Solutions

on:
  workflow_dispatch:  # Allows manual runs
  schedule:
    - cron: "0 8 * * 6"  # Runs every Saturday at 8 AM

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Updated version

      - name: Sync LeetCode Solutions
        uses: jclark-14/leetcode-sync@master  # Use your fork
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION_TOKEN }}
          destination-folder: solutions
          verbose: true
          commit-header: "[LeetCode Sync]"
      - name: List Repository Files for Debugging
        run: ls -R
